version: '3.9'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - ./.env
    restart: always
volumes:
  db-data:
